"""empty message

Revision ID: 6c6b0b2f66ed
Revises: 06a3b66ed845
Create Date: 2025-06-08 06:46:46.275885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6b0b2f66ed'
down_revision = '06a3b66ed845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleepTime', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wakeTime', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('wakeTime')
        batch_op.drop_column('sleepTime')

    # ### end Alembic commands ###
