"""empty message

Revision ID: 7936cd514e8d
Revises: 6c6b0b2f66ed
Create Date: 2025-06-08 06:52:02.045517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7936cd514e8d'
down_revision = '6c6b0b2f66ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wake_time', sa.Integer(), nullable=True))
        batch_op.drop_column('sleepTime')
        batch_op.drop_column('wakeTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wakeTime', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sleepTime', sa.INTEGER(), nullable=True))
        batch_op.drop_column('wake_time')
        batch_op.drop_column('sleep_time')

    # ### end Alembic commands ###
